### ISSUE TITLE
Github CI failing on forks

### ISSUE THREAD

**Issue by AyeGill** [LocalCharts/forest#7]
My fork of this repo is constantly generating CI errors because of some authentication problem.

Example:
![image](https://github.com/LocalCharts/forest/assets/2692879/dda104c9-7911-4395-99b2-df24c9830ba5)

This is a bit unfortunate given that forking is the intended way of contributing to the forest.

**Comment by AyeGill** [comment]
I think you can make the CI stuff conditional on running in the actual LocalCharts/forest repo by adding a line like `if: github.repository == 'LocalCharts/forest'`, as suggested in the documentation [here](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif).

I don't really want to make a PR for this myself because I have no way of testing it.

**Comment by olynch** [comment]
Ah, sounds good to me! Also, I have invited you as a collaborator so you don't have to make PRs in the future.
